apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
    tryImportMissing: true
  artifacts:
  - image: mmerguoum/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'
  - image: mmerguoum/clientside
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.vue'
    


