apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
    tryImportMissing: true #turn it false when you build all
  artifacts:
  - image: shaimeur/ecom
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'


