apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  #  local:
  #   push: false
  googleCloudBuild:
    projectId: listcoins
  artifacts:
  - image: us.gcr.io/listcoins/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - dest: .
        src: 'src/**/*.ts'


